# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=40)),
                ('max_sessions', models.IntegerField()),
                ('native_theme', models.CharField(choices=[('none', 'None'), ('starbucks', 'Starbucks'), ('m&m', 'M&M')], max_length=20)),
                ('rewarded_video', models.BooleanField(default=False)),
                ('rescue_video', models.BooleanField(default=False)),
                ('lose_video', models.BooleanField(default=False)),
                ('win_video', models.BooleanField(default=False)),
                ('preroll_video', models.BooleanField(default=False)),
                ('resme_game_video', models.BooleanField(default=False)),
                ('app_startup_video', models.BooleanField(default=False)),
                ('cool_down', models.BooleanField(default=False)),
                ('sponsored_enable', models.BooleanField(default=False)),
                ('sponsored_frequency', models.IntegerField()),
                ('location_wallpaper', models.BooleanField(default=False)),
            ],
        ),
    ]
