# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='resme_game_video',
            new_name='resume_game_video',
        ),
        migrations.AlterField(
            model_name='config',
            name='max_sessions',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='config',
            name='native_theme',
            field=models.CharField(choices=[('none', 'None'), ('starbucks', 'Starbucks'), ('m&m', 'M&M')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='config',
            name='sponsored_frequency',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
