# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20161202_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='rewarded_video',
        ),
    ]
