# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_config_rewarded_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='resume_game_video',
        ),
        migrations.AddField(
            model_name='config',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
